/**
 * LifePass AI — Temporary Development Fixtures for Citizen Notifications
 *
 * CAUTION / NOTICE:
 * This file contains strictly labelled development fixtures for UI testing
 * during Notifications citizen mobile frontend implementation.
 *
 * DO NOT represent this fixture data as real backend notifications or claim
 * that notifications were generated by live server-side events.
 * Authoritative schema: docs/DATABASE_SCHEMA.md Section 7, docs/BACKEND_SPEC.md Section 11,
 * and docs/FRONTEND_SPEC.md Section 2.
 */

import { ApiError } from '@lifepass/shared';

export type NotificationType =
  | 'new_institution_request'
  | 'consent_decision_needed'
  | 'consent_approved'
  | 'request_expired'
  | 'processing_completed'
  | 'record_status_change';

export interface NotificationItem {
  id: string;
  type: NotificationType;
  title: string;
  body: string;
  data?: {
    request_id?: string;
    record_id?: string;
    institution_name?: string;
    action_url?: string;
  };
  read_at: string | null;
  created_at: string;
}

// In-memory mutable fixture state to support "mark as read" in the UI
let mockNotifications: NotificationItem[] = [
  // 1. Unread Actionable Notification (Linked to Pending Education Loan Request)
  {
    id: 'notif-001',
    type: 'consent_decision_needed',
    title: 'Consent Decision Required',
    body: 'Demo Financial Institution has requested access to 5 records for your Education Loan Application. Review and grant explicit consent.',
    data: {
      request_id: 'req-edu-001',
      institution_name: 'Demo Financial Institution (Demo Fixture)',
    },
    read_at: null,
    created_at: new Date(Date.now() - 25 * 60 * 1000).toISOString(), // 25 mins ago
  },

  // 2. Unread Notification (New institution request notification)
  {
    id: 'notif-002',
    type: 'new_institution_request',
    title: 'New Verification Request',
    body: 'Demo Financial Institution submitted an application access request under Education Loan Requirement Profile.',
    data: {
      request_id: 'req-edu-001',
      institution_name: 'Demo Financial Institution (Demo Fixture)',
    },
    read_at: null,
    created_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(), // 2 hours ago
  },

  // 3. Read Notification (Processing completed)
  {
    id: 'notif-003',
    type: 'processing_completed',
    title: 'Document Processing Completed',
    body: 'Your Aadhaar Card (National Identity) was securely parsed and metadata extracted. Ready for matching.',
    data: {
      record_id: 'dev-fix-001',
    },
    read_at: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(), // 6 hours ago
  },

  // 4. Read Notification (Consent approved)
  {
    id: 'notif-004',
    type: 'consent_approved',
    title: 'Consent Granted',
    body: 'You authorized Apex Capital Partners to access 2 records for Credit Assessment & Financial Verification until next month.',
    data: {
      request_id: 'req-active-002',
      institution_name: 'Apex Capital Partners (Demo Fixture)',
    },
    read_at: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(), // 3 days ago
  },

  // 5. Read Notification (Record status change)
  {
    id: 'notif-005',
    type: 'record_status_change',
    title: 'Record Status Updated',
    body: 'Income Tax Return (ITR-V FY2024) is marked as processed in your personal record vault.',
    data: {
      record_id: 'dev-fix-004',
    },
    read_at: new Date(Date.now() - 48 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
  },

  // 6. Read Notification (Request expired)
  {
    id: 'notif-006',
    type: 'request_expired',
    title: 'Access Request Expired',
    body: 'The tenancy verification request from Prime Properties Leasing has expired and was automatically closed.',
    data: {
      request_id: 'req-exp-004',
      institution_name: 'Prime Properties Leasing (Demo Fixture)',
    },
    read_at: new Date(Date.now() - 72 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

/**
 * Fixture resolver to retrieve notifications list.
 */
export async function getFixtureNotifications(): Promise<NotificationItem[]> {
  await new Promise((resolve) => setTimeout(resolve, 300));
  return mockNotifications.map((n) => ({ ...n }));
}

/**
 * Mark a single notification as read in fixture memory.
 */
export async function markFixtureNotificationRead(
  notificationId: string
): Promise<NotificationItem> {
  await new Promise((resolve) => setTimeout(resolve, 150));

  const index = mockNotifications.findIndex((n) => n.id === notificationId);
  if (index === -1) {
    const error: ApiError = {
      code: 'NOT_FOUND',
      message: `Notification "${notificationId}" not found.`,
    };
    throw error;
  }

  mockNotifications[index] = {
    ...mockNotifications[index],
    read_at: new Date().toISOString(),
  };

  return { ...mockNotifications[index] };
}

/**
 * Mark all notifications as read in fixture memory.
 */
export async function markAllFixtureNotificationsRead(): Promise<NotificationItem[]> {
  await new Promise((resolve) => setTimeout(resolve, 200));

  const now = new Date().toISOString();
  mockNotifications = mockNotifications.map((n) => ({
    ...n,
    read_at: n.read_at || now,
  }));

  return mockNotifications.map((n) => ({ ...n }));
}
